"""
ICON TRACE - material master.

Lifted verbatim from v4's MATERIALS array, which was the only copy: the
screen could edit it, but nothing was saved and every change died with the
page. This is the seed for the material table, after which the database is
the master and this file is only how an empty one is filled.

TWO THINGS THAT LOOK WRONG AND ARE NOT

  * wattage is a STRING. materialsFor() matches a back label to a model
    with `mat.watt === m.watt`, and MODELS carries '635', not 635. Stored
    as a number the label silently applies to no model at all.

  * qpm is a number when both series consume the same and a {G2X, G12R}
    pair when they do not. Figures come from the Consumption BOM sheets.
    A material with qpm null is deliberately blank - stores has not
    confirmed it, and inventing one would make consumption wrong from the
    first module.
"""

MAT_CATS = ['Cell',
 'Glass',
 'Frame',
 'Encapsulant',
 'Interconnect',
 'Tapes',
 'Junction box & sealant',
 'Labels & packing']

# Cell efficiency is a property of the CELL, not of the module. Module
# efficiency comes later from the Sun Simulator. The same vendor at a
# different efficiency is a DIFFERENT material for traceability.
CELL_EFF = ['25%',
 '25.1%',
 '25.2%',
 '25.3%',
 '25.35%',
 '25.4%',
 '25.5%',
 '25.6%',
 '25.7%']

MATERIALS = [{'n': 1,
  'name': 'Solar Cell',
  'size': '182.2 x 183.75 mm · >25% · 16 BB',
  'uom': 'Nos',
  'series': 'G2X',
  'qpm': 72,
  'cell': True,
  'cat': 'Cell',
  'makes': ['Lion Solar',
            'PT Nusa Solar',
            'Premier Energies',
            'Solar Space',
            'Tongwei Solar',
            'Yingfa'],
  'note': 'Full-size cell — cut in half at the stringer, so 72 make 144 '
          'half cells'},
 {'n': 2,
  'name': 'Solar Glass — Front',
  'size': '2272 x 1128 x 2 mm',
  'uom': 'Nos',
  'series': 'G2X',
  'qpm': 1,
  'cat': 'Glass',
  'makes': ['Borosil', 'Kibing', 'Waaree', 'Xinyi']},
 {'n': 3,
  'name': 'Solar Glass — Rear',
  'size': '2272 x 1128 x 2 mm · 3 hole · grid printed',
  'uom': 'Nos',
  'series': 'G2X',
  'qpm': 1,
  'cat': 'Glass',
  'makes': ['Borosil', 'Kibing', 'Waaree', 'Xinyi']},
 {'n': 4,
  'name': 'Aluminium Frame',
  'size': '2278 x 1134 x 30 mm',
  'uom': 'Set',
  'series': 'G2X',
  'qpm': 1,
  'cat': 'Frame',
  'makes': ['Aluvoltec',
            'Jiangsu Yuejia',
            'Jiangyin Yuanshuo (YS)',
            'Ralpro Techno',
            'Shanti Green',
            'Sudarshan']},
 {'n': 5,
  'name': 'Solar Cell',
  'size': '182.2 x 210 mm · >25% · 16 BB',
  'uom': 'Nos',
  'series': 'G12R',
  'qpm': 66,
  'cell': True,
  'cat': 'Cell',
  'makes': ['Lion Solar',
            'PT Nusa Solar',
            'Premier Energies',
            'Solar Space',
            'Tongwei Solar',
            'Yingfa'],
  'note': 'Full-size cell — cut in half at the stringer, so 66 make 132 '
          'half cells'},
 {'n': 6,
  'name': 'Solar Glass — Front',
  'size': '2376 x 1128 x 2 mm',
  'uom': 'Nos',
  'series': 'G12R',
  'qpm': 1,
  'cat': 'Glass',
  'makes': ['Borosil', 'Kibing', 'Waaree', 'Xinyi']},
 {'n': 7,
  'name': 'Solar Glass — Rear',
  'size': '2376 x 1128 x 2 mm · 3 hole · grid printed',
  'uom': 'Nos',
  'series': 'G12R',
  'qpm': 1,
  'cat': 'Glass',
  'makes': ['Borosil', 'Kibing', 'Waaree', 'Xinyi']},
 {'n': 8,
  'name': 'Aluminium Frame',
  'size': '2382 x 1134 x 30 mm',
  'uom': 'Set',
  'series': 'G12R',
  'qpm': 1,
  'cat': 'Frame',
  'makes': ['Aluvoltec',
            'Jiangsu Yuejia',
            'Jiangyin Yuanshuo (YS)',
            'Ralpro Techno',
            'Shanti Green',
            'Sudarshan']},
 {'n': 9,
  'name': 'Encapsulant',
  'size': 'EPE / EPE · 460 GSM',
  'uom': 'Sqm',
  'series': '',
  'qpm': {'G2X': 5.14, 'G12R': 5.38},
  'cat': 'Encapsulant',
  'makes': ['Alishan', 'Knack', 'RenewSys', 'Sheetsol']},
 {'n': 12,
  'name': 'Cell Inter Connector',
  'size': '0.26 mm round wire',
  'uom': 'Kg',
  'series': '',
  'qpm': {'G2X': 0.178, 'G12R': 0.198},
  'cat': 'Interconnect',
  'makes': ['Dhash', 'Geba Copper', 'Juren', 'Sekhani Renewables', 'Valeo'],
  'note': 'Interconnect ribbon — joins cells at the stringer'},
 {'n': 13,
  'name': 'String Inter Connector — Centre',
  'size': '6.0 x 0.40 mm',
  'uom': 'Kg',
  'series': '',
  'qpm': 0.024,
  'cat': 'Interconnect',
  'makes': ['Dhash', 'Geba Copper', 'Juren', 'Sekhani Renewables', 'Valeo'],
  'note': 'Bus ribbon'},
 {'n': 14,
  'name': 'String Inter Connector — Edge',
  'size': '4.0 x 0.40 mm',
  'uom': 'Kg',
  'series': '',
  'qpm': 0.028,
  'cat': 'Interconnect',
  'makes': ['Dhash', 'Geba Copper', 'Juren', 'Sekhani Renewables', 'Valeo'],
  'note': 'Bus ribbon'},
 {'n': 19,
  'name': 'Flux',
  'size': '—',
  'uom': 'Ltr',
  'series': '',
  'qpm': 0.022,
  'cat': 'Interconnect',
  'makes': ['RCPV']},
 {'n': 20,
  'name': 'Cell Alignment Tape',
  'size': '8 mm width',
  'uom': 'Mtr',
  'series': '',
  'qpm': 1,
  'cat': 'Tapes',
  'makes': ['H.B. Fuller', 'Sunsol']},
 {'n': 22,
  'name': 'Edge Sealing Tape',
  'size': '30 mm width',
  'uom': 'Mtr',
  'series': '',
  'qpm': {'G2X': 7, 'G12R': 7.1},
  'cat': 'Tapes',
  'makes': ['H.B. Fuller', 'Sunsol']},
 {'n': 21,
  'name': 'Lead Bending Tape',
  'size': '20 mm width',
  'uom': 'Mtr',
  'series': '',
  'qpm': None,
  'cat': 'Tapes',
  'makes': ['H.B. Fuller', 'Sunsol'],
  'offbom': True},
 {'n': 23,
  'name': 'EPE Strip (Output Patti)',
  'size': '—',
  'uom': 'Sqm',
  'series': '',
  'qpm': None,
  'cat': 'Encapsulant',
  'makes': ['RenewSys'],
  'offbom': True},
 {'n': 10,
  'name': 'Junction Box 30 A',
  'size': '0.4 mtr',
  'uom': 'Nos',
  'series': '',
  'qpm': 1,
  'cat': 'Junction box & sealant',
  'group': 'JB',
  'makes': ['Dhash', 'GenX', 'QC Solar']},
 {'n': 11,
  'name': 'Junction Box 30 A',
  'size': '0.3 mtr',
  'uom': 'Nos',
  'series': '',
  'qpm': 1,
  'cat': 'Junction box & sealant',
  'group': 'JB',
  'makes': ['Dhash', 'GenX', 'QC Solar'],
  'legacy': True},
 {'n': 16,
  'name': 'Sealant (Frame + JB)',
  'size': '—',
  'uom': 'Kg',
  'series': '',
  'qpm': {'G2X': 0.34, 'G12R': 0.36},
  'cat': 'Junction box & sealant',
  'makes': ['Fasto', 'Huitian']},
 {'n': 17,
  'name': 'Potting Material — Part A',
  'size': 'resin · 6 parts of a 6:1 mix',
  'uom': 'Kg',
  'series': '',
  'qpm': 0.018857142857142857,
  'cat': 'Junction box & sealant',
  'makes': ['Fasto', 'Huitian'],
  'pot': 'A'},
 {'n': 18,
  'name': 'Potting Material — Part B',
  'size': 'hardener · 1 part of a 6:1 mix',
  'uom': 'Kg',
  'series': '',
  'qpm': 0.0031428571428571426,
  'cat': 'Junction box & sealant',
  'makes': ['Fasto', 'Huitian'],
  'pot': 'B'},
 {'n': 15,
  'name': 'RFID Sticker',
  'size': '—',
  'uom': 'Nos',
  'series': '',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Finotech', 'Kvell', 'Sunsol']},
 {'n': 29,
  'name': 'Barcode Label',
  'size': '—',
  'uom': 'Nos',
  'series': '',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Finotech', 'Kvell', 'Sunsol'],
  'added': True},
 {'n': 30,
  'name': 'Pallet Packing',
  'size': '—',
  'uom': 'Nos',
  'series': '',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell', 'Sunsol'],
  'added': True},
 {'n': 24,
  'name': 'Back Label 590WP',
  'size': '—',
  'uom': 'Nos',
  'series': 'LABEL',
  'watt': '590',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell']},
 {'n': 25,
  'name': 'Back Label 600WP',
  'size': '—',
  'uom': 'Nos',
  'series': 'LABEL',
  'watt': '600',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell']},
 {'n': 26,
  'name': 'Back Label 610WP',
  'size': '—',
  'uom': 'Nos',
  'series': 'LABEL',
  'watt': '610',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell'],
  'added': True},
 {'n': 27,
  'name': 'Back Label 620WP',
  'size': '—',
  'uom': 'Nos',
  'series': 'LABEL',
  'watt': '620',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell']},
 {'n': 28,
  'name': 'Back Label 625WP',
  'size': '—',
  'uom': 'Nos',
  'series': 'LABEL',
  'watt': '625',
  'qpm': 1,
  'cat': 'Labels & packing',
  'makes': ['Kvell']}]
